<ul id="menu" class="page-sidebar-menu">
    <li {!! (Request::is('admin') ? 'class="active"' : '') !!}>
        <a href="{{ route('admin.dashboard') }}">
            <i class="fa fa-home"></i>
            <span class="title">Dashboard</span>
        </a>
    </li>
	<?php 
	use Cartalyst\Sentinel\Native\Facades\Sentinel;
	$user=(App\RoleUser::manager(Sentinel::getUser()->id));
					$privileges=json_decode($user->privileges,true);
				?>
				@if(!empty($privileges))
					@foreach($privileges as $key=>$value)
						@foreach(App\RoleUser::mainmanager($key) as $mainvalue)
						<li class="parent @if(isset($PARENT_ID))@if($PARENT_ID==$mainvalue->mng_id)active @endif @endif">
							<a href="javascript:">
								<i class="{{$mainvalue->class_name}}"></i>
								<span class="title">{{$mainvalue->manager_name}}</span>
								<span class="fa arrow"></span>
							</a>
							<ul class="sub-menu">
								@foreach($value as $key1=>$value1)
									@foreach(App\RoleUser::mainmanager($value1) as $subvalue)
									<li {!! (Request::is('cpmin/'.$subvalue->page_link) ? 'class="active" id="active"' : '') !!}>
										<a href="{{ URL::to('cpmin/'.$subvalue->page_link) }}">
										<i class="fa fa-angle-double-right"></i>
										{{$subvalue->manager_name}} <span class="badge">4</span>
										</a>
									</li>
									@endforeach
								@endforeach
							</ul>
						</li>
						@endforeach
					@endforeach
				@endif
				
				@if(empty($privileges))
					@foreach(App\Manager::manager() as $value)
					<li class="@if(isset($PARENT_ID))@if($PARENT_ID==$value->mng_id)active @endif @endif">
						<a href="javascript:">
						<i class="{{$value->class_name}}"></i>
						<span class="title">{{$value->manager_name}}</span>
						<span class="fa arrow"></span>
						</a>
						<ul class="sub-menu">
							@foreach(App\Manager::submanager($value->mng_id) as $subvalue)
							<li {!! (Request::is('cpmin/'.$subvalue->page_link) ? 'class="active" id="active"' : '') !!}>
								<a href="{{ URL::to('cpmin/'.$subvalue->page_link) }}">
									<i class="fa fa-angle-double-right"></i>
								{{$subvalue->manager_name}} 
								@php
									$userData=App\User::leftjoin('role_users', 'role_users.user_id', '=', 'users.id')->leftjoin('roles', 'roles.id', '=', 'role_users.role_id')->where('roles.slug', 'user')->where('profile_status','=','pending')->count();
								@endphp
								@if ($subvalue->page_link == 'user/pending-customers')
									<span class="badge">{{$userData}}</span>
								@endif
								
								</a>
							</li>
							@endforeach
						</ul>
					</li>
				@endforeach
				@endif
	
    <!-- Menus generated by CRUD generator -->
    @include('admin/layouts/menu')
</ul>
